Repository minio/console, pull requests merged in 2020-09, with the labels that each got.

#258 Endpoints for update Minio/Console certificates and update Encryption configuration
  models/update_certificates_request.go
  restapi/admin_tenants.go
  restapi/admin_tenants_helper.go
  restapi/admin_tenants_helper_test.go
  restapi/admin_tenants_test.go
  restapi/embedded_spec.go
  restapi/k8s_client.go
  restapi/operations/admin_api/tenant_update_certificate.go
  restapi/operations/admin_api/tenant_update_certificate_parameters.go
  restapi/operations/admin_api/tenant_update_certificate_responses.go
  restapi/operations/admin_api/tenant_update_certificate_urlbuilder.go
  restapi/operations/admin_api/tenant_update_encryption.go
  restapi/operations/admin_api/tenant_update_encryption_parameters.go
  restapi/operations/admin_api/tenant_update_encryption_responses.go
  restapi/operations/admin_api/tenant_update_encryption_urlbuilder.go
  restapi/operations/console_api.go
  restapi/operator_client.go
  restapi/resource_quota.go
  restapi/resource_quota_test.go
  swagger.yml
Labels: security

#267 Fix Bug Creating Tenant Pull Secret
  go.mod
  go.sum
  restapi/admin_tenants.go
Labels: bug

#283 IV generation for ChaCha20 poly auth scheme
  pkg/auth/token.go
Labels: security

#289 Added file name visualization in file select
  portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
  portal-ui/src/screens/Console/Common/CredentialsPrompt/types.ts
  portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/utils/validationFunctions.ts
Labels: Dependency

#291 Add list objects api
  models/bucket_object.go
  models/list_objects_response.go
  restapi/client.go
  restapi/configure_console.go
  restapi/embedded_spec.go
  restapi/operations/console_api.go
  restapi/operations/user_api/list_objects.go
  restapi/operations/user_api/list_objects_parameters.go
  restapi/operations/user_api/list_objects_responses.go
  restapi/operations/user_api/list_objects_urlbuilder.go
  restapi/user_objects.go
  restapi/user_objects_test.go
  swagger.yml
Labels: enhancement
