Repository minio/console, pull requests merged in 2020-12, with the labels that each got.

#437 Connected retention policy modal
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/AddTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/DeleteTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetRetention.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/types.ts
  portal-ui/src/screens/Console/Common/FormComponents/RadioGroupSelector/RadioGroupSelector.tsx
  restapi/embedded_spec.go
  restapi/operations/console_api.go
  restapi/operations/user_api/delete_object_retention.go
  restapi/operations/user_api/delete_object_retention_parameters.go
  restapi/operations/user_api/delete_object_retention_responses.go
  restapi/operations/user_api/delete_object_retention_urlbuilder.go
  restapi/user_objects.go
  restapi/user_objects_test.go
  swagger.yml
Labels: UI

#454 Added tenant usage indicator
  portal-ui/src/screens/Console/Common/UsageBarWrapper/UsageBarWrapper.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
Labels: UI

#480 Remove alpine base and use UBI as the default base image
  Dockerfile.release
  Dockerfile.release.ubi
Labels: enhancement

#474 Added Edit minio image functionality
  portal-ui/src/screens/Console/Common/TableWrapper/TableActionIcons/DescriptionIcon.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/UpdateTenantModal.tsx
Labels: UI

#472 Remove TLS skip verify in wss/watch endpoint
  go.sum
  restapi/admin_tenants.go
  restapi/admin_tenants_test.go
  restapi/client.go
  restapi/operator_buckets.go
  restapi/ws_handle.go
Labels: security

#482 Disable Auto Complete for Operator Console
  portal-ui/src/screens/LoginPage/LoginPage.tsx
Labels: UI

#483 Refactor React Classes to Functions
  portal-ui/src/icons/AddIcon.tsx
  portal-ui/src/icons/AllBucketsIcon.tsx
  portal-ui/src/icons/BucketsIcon.tsx
  portal-ui/src/icons/ClustersIcon.tsx
  portal-ui/src/icons/ConfigurationsListIcon.tsx
  portal-ui/src/icons/ConsoleIcon.tsx
  portal-ui/src/icons/CopyIcon.tsx
  portal-ui/src/icons/CreateIcon.tsx
  portal-ui/src/icons/DashboardIcon.tsx
  portal-ui/src/icons/DeleteIcon.tsx
  portal-ui/src/icons/DownloadIcon.tsx
  portal-ui/src/icons/EgressIcon.tsx
  portal-ui/src/icons/GroupsIcon.tsx
  portal-ui/src/icons/HealIcon.tsx
  portal-ui/src/icons/IAMPoliciesIcon.tsx
  portal-ui/src/icons/LambdaNotificationsIcon.tsx
  portal-ui/src/icons/LicenseIcon.tsx
  portal-ui/src/icons/LogoutIcon.tsx
  portal-ui/src/icons/MirroringIcon.tsx
  portal-ui/src/icons/PermissionIcon.tsx
  portal-ui/src/icons/RemoveIcon.tsx
  portal-ui/src/icons/ServiceAccountIcon.tsx
  portal-ui/src/icons/ServiceAccountsIcon.tsx
  portal-ui/src/icons/ShareIcon.tsx
  portal-ui/src/icons/TraceIcon.tsx
  portal-ui/src/icons/UploadFile.tsx
  portal-ui/src/icons/UsageIcon.tsx
  portal-ui/src/icons/UsersIcon.tsx
  portal-ui/src/icons/WarpIcon.tsx
  portal-ui/src/icons/WatchIcon.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/DeleteBucket.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/DeleteObject.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/AddEvent.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/DeleteEvent.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/EnableBucketEncryption.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/SetAccessPolicy.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  portal-ui/src/screens/Console/Policies/AddPolicy.tsx
  portal-ui/src/screens/Console/Policies/DeletePolicy.tsx
  portal-ui/src/screens/Console/Users/AddUser.tsx
  portal-ui/src/screens/Console/Users/DeleteUser.tsx
  portal-ui/src/screens/Console/Users/Users.tsx
Labels: UI

#494 Fix bad import on Console TSX
  portal-ui/src/screens/Console/Account/ChangePasswordModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Users/Users.tsx
Labels: UI

#496 Moved notifications lambda pages to settings
  pkg/acl/endpoints.go
  pkg/acl/endpoints_test.go
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/Common/SlideOptions/SlideOptions.tsx
  portal-ui/src/screens/Console/Configurations/ConfigurationMain.tsx
  portal-ui/src/screens/Console/Configurations/ConfigurationPanels/ConfigurationsList.tsx
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfMySql.tsx
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfPostgres.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/AddNotificationEndpoint.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/ListNotificationEndpoints.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/NotificationTypeSelector.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/types.ts
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/utils.ts
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Menu/Menu.tsx
  portal-ui/src/screens/Console/NotificationEndopoints/AddNotificationEndpoint.tsx
  portal-ui/src/screens/Console/NotificationEndopoints/ListNotificationEndpoints.tsx
  portal-ui/src/screens/Console/NotificationEndopoints/types.ts
  portal-ui/src/screens/Console/NotificationEndopoints/utils.ts
Labels: UI

#502 Replace IDP with Identity Provider
  portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx
Labels: Operator

#503 Set Operator Logo for Operator Mode
  portal-ui/src/ProtectedRoutes.tsx
  portal-ui/src/actions.ts
  portal-ui/src/icons/minio_operator_logo.svg
  portal-ui/src/reducer.ts
  portal-ui/src/screens/Console/Account/Account.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  portal-ui/src/screens/Console/Menu/Menu.tsx
  portal-ui/src/screens/Console/Menu/types.ts
  portal-ui/src/types.ts
Labels: Operator

#505 Added notification for delete object
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
Labels: UI

#506 Added padding to error message in login screen
  portal-ui/src/screens/LoginPage/LoginPage.tsx
Labels: UI

#508 Run React Tests
  .github/workflows/react.yml
  portal-ui/package.json
  portal-ui/src/common/__tests__/utils.test.ts
  portal-ui/src/common/utils.ts
  portal-ui/yarn.lock
Labels: UI

#514 Introduce ErrorBlock component to display error text
  portal-ui/src/screens/Console/Account/Account.tsx
  portal-ui/src/screens/Console/Account/AddServiceAccount.tsx
  portal-ui/src/screens/Console/Account/ChangePasswordModal.tsx
  portal-ui/src/screens/Console/Account/DeleteServiceAccount.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/DeleteBucket.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/DeleteObject.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/AddTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetLegalHoldModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetRetention.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ShareFile.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/AddEvent.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/AddReplicationModal.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/DeleteEvent.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/EnableBucketEncryption.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/SetAccessPolicy.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
  portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
  portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
  portal-ui/src/screens/Console/Common/UsageBarWrapper/UsageBarWrapper.tsx
  portal-ui/src/screens/Console/Configurations/ConfigurationPanels/ConfigurationsList.tsx
  portal-ui/src/screens/Console/Configurations/ConfigurationPanels/WebhookPanel.tsx
  portal-ui/src/screens/Console/Configurations/CustomForms/EditConfiguration.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/AddNotificationEndpoint.tsx
  portal-ui/src/screens/Console/Configurations/NotificationEndpoints/ListNotificationEndpoints.tsx
  portal-ui/src/screens/Console/Dashboard/Dashboard.tsx
  portal-ui/src/screens/Console/Groups/AddGroup.tsx
  portal-ui/src/screens/Console/Groups/DeleteGroup.tsx
  portal-ui/src/screens/Console/Groups/Groups.tsx
  portal-ui/src/screens/Console/Groups/UsersSelectors.tsx
  portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
  portal-ui/src/screens/Console/Policies/AddPolicy.tsx
  portal-ui/src/screens/Console/Policies/DeletePolicy.tsx
  portal-ui/src/screens/Console/Policies/Policies.tsx
  portal-ui/src/screens/Console/Policies/PolicySelectors.tsx
  portal-ui/src/screens/Console/Policies/SetPolicy.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/AddPoolModal.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/ReplicationSetup.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/UpdateTenantModal.tsx
  portal-ui/src/screens/Console/Users/AddToGroup.tsx
  portal-ui/src/screens/Console/Users/AddUser.tsx
  portal-ui/src/screens/Console/Users/DeleteUser.tsx
  portal-ui/src/screens/Console/Users/GroupsSelectors.tsx
  portal-ui/src/screens/Console/Users/Users.tsx
  portal-ui/src/screens/shared/ErrorBlock.tsx
Labels: UI

#509 Integrate retention option during bucket creation on UI
  portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket.tsx
  portal-ui/src/screens/Console/Buckets/actions.ts
  portal-ui/src/screens/Console/Buckets/reducers.ts
  portal-ui/src/screens/Console/Buckets/types.tsx
Labels: UI

#515 Integrate Set Retention Config on existing Bucket in UI
  portal-ui/src/screens/Console/Buckets/ViewBucket/SetRetentionConfig.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
Labels: UI

#517 Added EC Parity correct values to add tenant modal
  portal-ui/src/common/__tests__/utils.test.ts
  portal-ui/src/common/types.ts
  portal-ui/src/common/utils.ts
  portal-ui/src/screens/Console/Account/Account.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/utils.ts
  swagger.yml
Labels: UI, bug

#519 Remove Duplicate Definitions on Swagger
  swagger.yml
Labels: bug

#533 Fixed class override issue
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Console.tsx
Labels: UI, bug

#537 Consolidate New Prompt Credentials - Subnet #1441
  portal-ui/src/screens/Console/Account/Account.tsx
  portal-ui/src/screens/Console/Common/CredentialsPrompt/types.ts
Labels: UI, bug
