Repository minio/console, pull requests merged in 2020-04, with the labels that each got.

#50 API to list and add Notification Endpoints
  models/add_notification_endpoint.go
  models/nofitication_service.go
  models/notif_endpoint_response.go
  models/notification_endpoint.go
  models/notification_endpoint_item.go
  restapi/admin_config.go
  restapi/admin_config_test.go
  restapi/admin_notification_endpoints.go
  restapi/admin_notification_endpoints_test.go
  restapi/configure_mcs.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/add_notification_endpoint.go
  restapi/operations/admin_api/add_notification_endpoint_parameters.go
  restapi/operations/admin_api/add_notification_endpoint_responses.go
  restapi/operations/admin_api/add_notification_endpoint_urlbuilder.go
  restapi/operations/admin_api/notification_endpoint_list.go
  restapi/operations/admin_api/notification_endpoint_list_parameters.go
  restapi/operations/admin_api/notification_endpoint_list_responses.go
  restapi/operations/admin_api/notification_endpoint_list_urlbuilder.go
  restapi/operations/mcs_api.go
  swagger.yml
Labels: enhancement

#68 [WIP] Added bulk functionality for add users to groups
  models/bulk_user_groups.go
  portal-ui/src/screens/Console/Users/AddToGroup.tsx
  portal-ui/src/screens/Console/Users/AddUser.tsx
  portal-ui/src/screens/Console/Users/GroupsSelectors.tsx
  portal-ui/src/screens/Console/Users/Users.tsx
  restapi/admin_users.go
  restapi/admin_users_test.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/bulk_update_users_groups.go
  restapi/operations/admin_api/bulk_update_users_groups_parameters.go
  restapi/operations/admin_api/bulk_update_users_groups_responses.go
  restapi/operations/admin_api/bulk_update_users_groups_urlbuilder.go
  restapi/operations/bulk_update_users_groups.go
  restapi/operations/bulk_update_users_groups_parameters.go
  restapi/operations/bulk_update_users_groups_responses.go
  restapi/operations/bulk_update_users_groups_urlbuilder.go
  restapi/operations/mcs_api.go
  swagger.yml
Labels: WIP

#79 Bug: User List not refreshing after delete
  portal-ui/src/screens/Console/Users/Users.tsx
Labels: UI, bug
