Repository minio/console, pull requests merged in 2020-11, with the labels that each got.

#380 Fixed issue with checkbox selection in table wrapper
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/CreateFolderModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Common/TableWrapper/TableWrapper.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/Trace/Trace.tsx
  portal-ui/src/screens/LoginPage/LoginPage.tsx
Labels: bug

#383 Add disabled functionality and fix styling for RadioGroupSelector
  portal-ui/src/screens/Console/Common/FormComponents/RadioGroupSelector/RadioGroupSelector.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
Labels: UI

#387 Migrated TableWrapper to use react-virtualized
  portal-ui/package.json
  portal-ui/src/index.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/Common/TableWrapper/TableActionButton.tsx
  portal-ui/src/screens/Console/Common/TableWrapper/TableWrapper.tsx
  portal-ui/src/screens/Console/Groups/Groups.tsx
  portal-ui/src/screens/Console/Groups/UsersSelectors.tsx
  portal-ui/src/screens/Console/NotificationEndopoints/ListNotificationEndpoints.tsx
  portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
  portal-ui/src/screens/Console/Policies/Policies.tsx
  portal-ui/src/screens/Console/Policies/PolicySelectors.tsx
  portal-ui/src/screens/Console/ServiceAccounts/ServiceAccounts.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Users/GroupsSelectors.tsx
  portal-ui/src/screens/Console/Users/Users.tsx
  portal-ui/yarn.lock
Labels: UI

#384 Adjust Modal form clear button font based on mockups
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
Labels: UI

#385 Edit Searchbar styling based on mockups
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
Labels: UI

#389 Fixed issue with object browser icons & long names
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
Labels: UI, bug

#397 Fixed issue with back arrows & navigation in object browser
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
  portal-ui/src/screens/Console/ObjectBrowser/actions.ts
  portal-ui/src/screens/Console/ObjectBrowser/reducers.ts
Labels: UI, bug

#399 Connected delete & download buttons for object details
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
Labels: UI

#420 Fix Tenant Details header
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
Labels: Operator, UI

#421 Connected object tags API
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/AddTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/DeleteTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
Labels: UI, WIP

#436 Legal hold modal implementation
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetLegalHoldModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/types.ts
Labels: UI

#445 Fixed object lock
  restapi/client.go
  restapi/user_buckets.go
  restapi/user_buckets_test.go
Labels: UI, bug

#452 Predefined list
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ShareFile.tsx
  portal-ui/src/screens/Console/Common/FormComponents/PredefinedList/PredefinedList.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfMySql.tsx
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfPostgres.tsx
  portal-ui/src/screens/Console/Groups/AddGroup.tsx
  portal-ui/src/screens/Console/Policies/SetPolicy.tsx
  portal-ui/src/screens/Console/Users/AddToGroup.tsx
  portal-ui/src/screens/Console/Users/AddUser.tsx
Labels: UI, enhancement

#382 Add set policy to multiple user/groups
  models/iam_entity.go
  models/set_policy_multiple_request.go
  restapi/admin_policies.go
  restapi/admin_policies_test.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/set_policy_multiple.go
  restapi/operations/admin_api/set_policy_multiple_parameters.go
  restapi/operations/admin_api/set_policy_multiple_responses.go
  restapi/operations/admin_api/set_policy_multiple_urlbuilder.go
  restapi/operations/console_api.go
  swagger.yml
Labels: enhancement
