Repository minio/console, pull requests merged in 2021-03, with the labels that each got.

#628 Limited input width size for forms in wide screens
  portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/PredefinedList/PredefinedList.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfMySql.tsx
  portal-ui/src/screens/Console/Configurations/CustomForms/ConfPostgres.tsx
Labels: UI, enhancement

#627 add console systemd service
  systemd/README.md
  systemd/console.service
Labels: enhancement

#642 Allowed edit in policies create form
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.24ccc614.chunk.js
  portal-ui/build/static/js/main.24ccc614.chunk.js.map
  portal-ui/build/static/js/main.cc2e1a78.chunk.js
  portal-ui/build/static/js/main.cc2e1a78.chunk.js.map
  portal-ui/src/screens/Console/Policies/AddPolicy.tsx
Labels: UI

#652 Remove user secret key from encrypted session token
  models/principal.go
  pkg/auth/token.go
  pkg/auth/token_test.go
  restapi/client.go
  restapi/configure_console.go
  restapi/embedded_spec.go
  restapi/error.go
  restapi/user_account.go
  restapi/user_account_test.go
  restapi/user_login.go
  restapi/user_login_test.go
  swagger.yml
Labels: security

#660 api for listing policies attatched to a bucket
  restapi/admin_policies.go
  restapi/admin_policies_test.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/list_policies_with_bucket.go
  restapi/operations/admin_api/list_policies_with_bucket_parameters.go
  restapi/operations/admin_api/list_policies_with_bucket_responses.go
  restapi/operations/admin_api/list_policies_with_bucket_urlbuilder.go
  restapi/operations/console_api.go
  swagger.yml
Labels: enhancement

#645 Added versioning edit in console
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.5dcc63ee.chunk.js
  portal-ui/build/static/js/main.5dcc63ee.chunk.js.map
  portal-ui/build/static/js/main.cc2e1a78.chunk.js
  portal-ui/build/static/js/main.cc2e1a78.chunk.js.map
  portal-ui/src/screens/Console/Buckets/ViewBucket/EnableVersioningModal.tsx
  portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
  restapi/client.go
  restapi/user_buckets.go
  restapi/user_buckets_test.go
Labels: UI, enhancement

#655 Interactive Feedback when list objects take a long time
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Common/TableWrapper/TableWrapper.tsx
Labels: enhancement
