Repository minio/console, pull requests merged in 2021-06, with the labels that each got.

#765 move to madmin-go package
  .github/workflows/codeql.yml
  cluster/config.go
  cmd/console/main.go
  cmd/console/server.go
  go.mod
  go.sum
  pkg/acl/config.go
  pkg/acl/endpoints.go
  pkg/acl/endpoints_test.go
  pkg/auth/idp/oauth2/config.go
  pkg/auth/ldap/config.go
  pkg/auth/token/config.go
  pkg/certs/certs.go
  pkg/subnet/config.go
  pkg/subnet/config_test.go
  pkg/subnet/subnet.go
  pkg/utils/parity.go
  pkg/utils/parity_test.go
  restapi/admin_arns_test.go
  restapi/admin_config.go
  restapi/admin_config_test.go
  restapi/admin_console.go
  restapi/admin_console_test.go
  restapi/admin_groups.go
  restapi/admin_groups_test.go
  restapi/admin_heal.go
  restapi/admin_heal_test.go
  restapi/admin_health_info.go
  restapi/admin_health_info_test.go
  restapi/admin_info_test.go
  restapi/admin_nodes_test.go
  restapi/admin_policies.go
  restapi/admin_policies_test.go
  restapi/admin_profiling.go
  restapi/admin_profiling_test.go
  restapi/admin_remote_buckets.go
  restapi/admin_service_test.go
  restapi/admin_tenants.go
  restapi/admin_test.go
  restapi/admin_tiers.go
  restapi/admin_tiers_test.go
  restapi/admin_trace.go
  restapi/admin_trace_test.go
  restapi/admin_users.go
  restapi/admin_users_test.go
  restapi/client-admin.go
  restapi/config.go
  restapi/error.go
  restapi/tls.go
  restapi/user_account.go
  restapi/user_account_test.go
  restapi/user_bucket_quota.go
  restapi/user_buckets.go
  restapi/user_buckets_test.go
  restapi/user_login.go
  restapi/user_login_test.go
  restapi/user_objects_test.go
  restapi/user_service_accounts.go
  restapi/user_service_accounts_test.go
Labels: Needed

#795 Added URL navigation to tenant details
  pkg/acl/endpoints.go
  pkg/acl/endpoints_test.go
  portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/License/LicenseModal.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/PodsSummary.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/PoolsSummary.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantLicense.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSummary.tsx
  portal-ui/src/screens/Console/Tenants/actions.ts
  portal-ui/src/screens/Console/Tenants/reducer.ts
  portal-ui/src/screens/Console/Tenants/types.ts
  portal-ui/src/screens/Console/Users/ListUsers.tsx
  portal-ui/src/screens/Console/Users/UserServiceAccountsPanel.tsx
Labels: enhancement

#796 Add missing resource to cluster role
  k8s/operator-console/base/console-cluster-role.yaml
  restapi/admin_tenants.go
Labels: bug

#797 Removed not available comparison
  portal-ui/src/screens/Console/DirectCSI/DirectCSIDrives.tsx
Labels: bug

#803 Implemented an autocomplete component
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/css/2.6b0fc1a4.chunk.css
  portal-ui/build/static/css/2.6b0fc1a4.chunk.css.map
  portal-ui/build/static/css/2.c5a51b70.chunk.css
  portal-ui/build/static/css/2.c5a51b70.chunk.css.map
  portal-ui/build/static/css/main.8cfac526.chunk.css
  portal-ui/build/static/css/main.8cfac526.chunk.css.map
  portal-ui/build/static/css/main.a19f3d53.chunk.css
  portal-ui/build/static/css/main.a19f3d53.chunk.css.map
  portal-ui/build/static/js/2.1fe0b485.chunk.js
  portal-ui/build/static/js/2.1fe0b485.chunk.js.LICENSE.txt
  portal-ui/build/static/js/2.b7e1d397.chunk.js
  portal-ui/build/static/js/2.b7e1d397.chunk.js.LICENSE.txt
  portal-ui/build/static/js/2.c8e96199.chunk.js
  portal-ui/build/static/js/2.c8e96199.chunk.js.LICENSE.txt
  portal-ui/build/static/js/main.8d2bc888.chunk.js
  portal-ui/build/static/js/main.8d2bc888.chunk.js.map
  portal-ui/build/static/js/main.db678f65.chunk.js
  portal-ui/build/static/js/main.db678f65.chunk.js.map
  portal-ui/build/static/js/main.ed3c7e50.chunk.js
  portal-ui/build/static/js/main.ed3c7e50.chunk.js.map
  portal-ui/build/static/js/runtime-main.43a31377.js
  portal-ui/build/static/js/runtime-main.43a31377.js.map
  portal-ui/build/static/js/runtime-main.f48e99e5.js
  portal-ui/build/static/js/runtime-main.f48e99e5.js.map
  portal-ui/package.json
  portal-ui/src/screens/Console/Account/Account.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/AddEvent.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/BucketEventsPanel.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/BucketLifecyclePanel.tsx
  portal-ui/src/screens/Console/Common/FormComponents/AutocompleteWrapper/AutocompleteWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/InputBoxWrapper/InputBoxWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/common/styleLibrary.ts
  portal-ui/src/screens/Console/DirectCSI/DirectCSIDrives.tsx
  portal-ui/src/screens/Console/License/LicenseModal.tsx
  portal-ui/src/screens/Console/Logs/LogSearch/LogsSearchMain.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/types.ts
  portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/PoolsSummary.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSummary.tsx
  portal-ui/src/screens/Console/Tenants/actions.ts
  portal-ui/src/screens/Console/Users/UserServiceAccountsPanel.tsx
  portal-ui/yarn.lock
Labels: enhancement

#808 Added create namespace API
  models/namespace.go
  restapi/admin_namespaces.go
  restapi/admin_namespaces_test.go
  restapi/configure_console.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/create_namespace.go
  restapi/operations/admin_api/create_namespace_parameters.go
  restapi/operations/admin_api/create_namespace_responses.go
  restapi/operations/admin_api/create_namespace_urlbuilder.go
  restapi/operations/console_api.go
  swagger.yml
Labels: enhancement

#812 fix: allow TLS access on multiple SNI certs
  cmd/console/server.go
  pkg/certs/certs.go
  restapi/config.go
  restapi/configure_console.go
Labels: Needed

#816 Changed field names & removed bottom texts
  portal-ui/src/screens/LoginPage/LoginPage.tsx
Labels: Needed

#815 Fixed issue with comparison & prettier
  portal-ui/src/screens/Console/Configurations/TiersConfiguration/AddTierConfiguration.tsx
Labels: bug

#818 fix: do not use var to define global sets
  restapi/client.go
  restapi/user_login.go
Labels: Needed
