Repository minio/console, pull requests merged in 2021-02, with the labels that each got.

#581 Upgrade console to use operator v4.0.0
  go.mod
  go.sum
  restapi/admin_subscription.go
  restapi/admin_tenants.go
  restapi/admin_tenants_helper.go
  restapi/admin_tenants_helper_test.go
  restapi/admin_tenants_test.go
  restapi/operator_client.go
Labels: Operator

#591 Changed policy API to receive name param in query instead or URL
  portal-ui/src/screens/Console/Policies/DeletePolicy.tsx
  restapi/embedded_spec.go
  restapi/operations/admin_api/policy_info.go
  restapi/operations/admin_api/policy_info_parameters.go
  restapi/operations/admin_api/policy_info_urlbuilder.go
  restapi/operations/admin_api/remove_policy.go
  restapi/operations/admin_api/remove_policy_parameters.go
  restapi/operations/admin_api/remove_policy_urlbuilder.go
  restapi/operations/console_api.go
  swagger.yml
Labels: UI, bug

#596 Move Tenant from Modal to Page
  pkg/acl/endpoints.go
  pkg/acl/endpoints_test.go
  portal-ui/src/screens/Console/Common/GenericWizard/GenericWizard.tsx
  portal-ui/src/screens/Console/Common/GenericWizard/WizardPage.tsx
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
Labels: UI

#609 Get Tenants endpoints check hostname
  restapi/admin_tenants.go
Labels: Operator
