Repository minio/console, pull requests merged in 2021-04, with the labels that each got.

#678 Operator UI improvements
  models/session_response.go
  pkg/auth/idp/oauth2/provider.go
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/2.44b7c49b.chunk.js
  portal-ui/build/static/js/2.44b7c49b.chunk.js.LICENSE.txt
  portal-ui/build/static/js/2.fff5f618.chunk.js
  portal-ui/build/static/js/2.fff5f618.chunk.js.LICENSE.txt
  portal-ui/build/static/js/main.53ad5aa5.chunk.js
  portal-ui/build/static/js/main.53ad5aa5.chunk.js.map
  portal-ui/build/static/js/main.fa0873e1.chunk.js
  portal-ui/build/static/js/main.fa0873e1.chunk.js.map
  portal-ui/src/screens/Console/Buckets/ViewBucket/DeleteEvent.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantSize.tsx
  portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
  portal-ui/src/screens/Console/Tenants/TenantsMain.tsx
  portal-ui/src/screens/Console/reducer.ts
  portal-ui/src/screens/Console/types.ts
  portal-ui/src/screens/LoginPage/LoginPage.tsx
  restapi/admin_subscription.go
  restapi/embedded_spec.go
  restapi/error.go
  restapi/user_session.go
  swagger.yml
Labels: Operator

#684 Fixed double scroll issue in modal wizard
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.92bfa60e.chunk.js
  portal-ui/build/static/js/main.92bfa60e.chunk.js.map
  portal-ui/build/static/js/main.fc2473f5.chunk.js
  portal-ui/build/static/js/main.fc2473f5.chunk.js.map
  portal-ui/src/screens/Console/Buckets/ListBuckets/BulkReplicationModal.tsx
  portal-ui/src/screens/Console/Common/GenericWizard/GenericWizard.tsx
  portal-ui/src/screens/Console/Common/GenericWizard/WizardPage.tsx
Labels: Needed, UI, bug

#700 Added log search & prometheus extra params configuration
  go.mod
  go.sum
  models/create_tenant_request.go
  models/log_search_configuration.go
  models/prometheus_configuration.go
  portal-ui/src/common/types.ts
  portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Configure.tsx
  portal-ui/src/screens/Console/Tenants/reducer.ts
  portal-ui/src/screens/Console/Tenants/types.ts
  restapi/admin_tenants.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/list_users_with_bucket_access.go
  restapi/operations/admin_api/list_users_with_bucket_access_parameters.go
  restapi/operations/admin_api/list_users_with_bucket_access_responses.go
  restapi/operations/admin_api/list_users_with_bucket_access_urlbuilder.go
  swagger.yml
Labels: UI

#703 Fixes an issue with empty logsearch & prometheus configurations
  restapi/admin_tenants.go
Labels: Needed, UI, bug
