Repository minio/console, pull requests merged in 2021-05, with the labels that each got.

#710 Added direct-csi API support to console
  models/csi_format_error_response.go
  models/format_configuration.go
  models/format_direct_c_s_i_drives_response.go
  restapi/admin_direct_csi.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/direct_c_s_i_format_drive.go
  restapi/operations/admin_api/direct_c_s_i_format_drive_parameters.go
  restapi/operations/admin_api/direct_c_s_i_format_drive_responses.go
  restapi/operations/admin_api/direct_c_s_i_format_drive_urlbuilder.go
  restapi/operations/console_api.go
  swagger.yml
Labels: Needed, enhancement

#725 Fixed missing object in swagger
  restapi/embedded_spec.go
  swagger.yml
Labels: Needed, bug

#724 Update Console metrics dashboard
  images/pic1.png
Labels: documentation

#729 Fix bug when adding multiple built-in users
  restapi/admin_tenants.go
Labels: Needed, bug

#730 Remove duplicated logic
  restapi/admin_tenants.go
Labels: Needed, bug

#732 Fix NodeSelector Screen
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.b74c83f1.chunk.js
  portal-ui/build/static/js/main.b74c83f1.chunk.js.map
  portal-ui/build/static/js/main.d6310664.chunk.js
  portal-ui/build/static/js/main.d6310664.chunk.js.map
  portal-ui/src/common/types.ts
  portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Affinity.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantYAML.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/utils.ts
  portal-ui/src/screens/Console/Tenants/reducer.ts
  portal-ui/src/screens/Console/Tenants/types.ts
  restapi/admin_tenants.go
Labels: Needed, bug

#731 Update Console Prometheus Widgets
  restapi/admin_info.go
Labels: Needed, bug

#737 Fixed Console Widgets to match grafana information
  portal-ui/package.json
  portal-ui/src/common/utils.ts
  portal-ui/src/screens/Console/Dashboard/Prometheus/PrDashboard.tsx
  portal-ui/src/screens/Console/Dashboard/Prometheus/utils.ts
  portal-ui/yarn.lock
  restapi/admin_info.go
  restapi/embedded_spec.go
  restapi/operations/admin_api/admin_info_parameters.go
  restapi/operations/admin_api/admin_info_urlbuilder.go
  swagger.yml
Labels: Needed, bug

#739 More Widgets fixes
  portal-ui/src/screens/Console/Dashboard/Prometheus/utils.ts
Labels: UI

#743 Added sync icon to get information button
  portal-ui/src/icons/SyncIcon.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
  portal-ui/src/screens/Console/Dashboard/Prometheus/PrDashboard.tsx
Labels: enhancement

#760 Bug fix in bucket users
  portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
  restapi/admin_users.go
Labels: bug

#763 Fixed issue with graphs that are not showing series correctly
  portal-ui/src/screens/Console/Dashboard/Prometheus/utils.ts
Labels: UI, bug

#764 Fix PVC list so it's only tenant PVCs. Fix NPE on pod listing.
  portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
  restapi/admin_tenants.go
  restapi/admin_volumes.go
Labels: bug

#767 20 seconds timeout removal
  restapi/user_objects.go
Labels: Needed, bug
