Repository minio/console, pull requests merged in 2021-07, with the labels that each got.

#861 fix: change password is implicit
  pkg/acl/endpoints.go
  pkg/acl/endpoints_test.go
  restapi/user_account.go
  restapi/user_account_test.go
Labels: Needed

#874 fix: properly support FS/Gateway mode
  go.mod
  go.sum
  restapi/admin_health_info_test.go
  restapi/user_bucket_quota.go
  restapi/user_buckets.go
Labels: Needed

#882 Fixed policy page crash
  portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
Labels: UI, bug

#876 Fix bug when deleting objects with % in the name
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/DeleteObject.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
Labels: bug

#880 Added FS Support & blocked non usable functionality in console
  go.sum
  models/list_buckets_response.go
  models/session_response.go
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/2.55ef6ad7.chunk.js
  portal-ui/build/static/js/2.55ef6ad7.chunk.js.LICENSE.txt
  portal-ui/build/static/js/2.dd405112.chunk.js
  portal-ui/build/static/js/2.dd405112.chunk.js.LICENSE.txt
  portal-ui/build/static/js/main.059e1608.chunk.js
  portal-ui/build/static/js/main.059e1608.chunk.js.map
  portal-ui/build/static/js/main.a608e767.chunk.js
  portal-ui/build/static/js/main.a608e767.chunk.js.map
  portal-ui/src/ProtectedRoutes.tsx
  portal-ui/src/actions.ts
  portal-ui/src/reducer.ts
  portal-ui/src/screens/Console/Buckets/BucketDetails/BucketDetails.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/AddTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/DeleteTagModal.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ShareFile.tsx
  portal-ui/src/screens/Console/Configurations/ConfigurationMain.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/DeletePod.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/PodsSummary.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/reducer.ts
  portal-ui/src/screens/Console/types.ts
  portal-ui/src/types.ts
  restapi/embedded_spec.go
  restapi/operations/admin_api/subscription_refresh.go
  restapi/operations/admin_api/subscription_refresh_parameters.go
  restapi/operations/admin_api/subscription_refresh_responses.go
  restapi/operations/admin_api/subscription_refresh_urlbuilder.go
  restapi/operations/admin_api/subscription_validate.go
  restapi/operations/admin_api/subscription_validate_parameters.go
  restapi/operations/admin_api/subscription_validate_responses.go
  restapi/operations/admin_api/subscription_validate_urlbuilder.go
  restapi/operations/console_api.go
  restapi/user_session.go
  swagger-console.yml
Labels: UI, enhancement

#887 fix: subnet health triggering OOM, infinite loop
  restapi/client-admin.go
Labels: Needed

#888 Added loading splash screen
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.439bfd00.chunk.js
  portal-ui/build/static/js/main.439bfd00.chunk.js.map
  portal-ui/build/static/js/main.a608e767.chunk.js
  portal-ui/build/static/js/main.a608e767.chunk.js.map
  portal-ui/build/styles/root-styles.css
  portal-ui/public/index.html
  portal-ui/public/styles/root-styles.css
  portal-ui/src/index.tsx
  portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
  portal-ui/src/screens/LoginPage/LoginPage.tsx
Labels: UI

#890 Removed log search error message in console logs
  portal-ui/src/screens/Console/Logs/LogSearch/LogsSearchMain.tsx
  portal-ui/src/screens/Console/Logs/LogsMain.tsx
  restapi/config.go
  restapi/user_session.go
Labels: Needed, bug

#895 Added Component height & removed wrap in file selector component elements
  portal-ui/build/asset-manifest.json
  portal-ui/build/index.html
  portal-ui/build/static/js/main.16e6cd68.chunk.js
  portal-ui/build/static/js/main.16e6cd68.chunk.js.map
  portal-ui/build/static/js/main.2cc5eec9.chunk.js
  portal-ui/build/static/js/main.2cc5eec9.chunk.js.map
  portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
  portal-ui/src/screens/Console/Users/ListUsers.tsx
Labels: UI, bug

#900 Fix bug not allowing to add webhooks
  portal-ui/src/screens/Console/Configurations/utils.ts
Labels: bug

#912 Fix Bug Delete Folder
  restapi/user_objects.go
Labels: bug
