Repository minio/console, pull requests merged in 2022-04, with the labels that each got.

#1787 Node Labels Test
  .github/workflows/jobs.yaml
  operator-integration/tenant_test.go
Labels: Operator

#1797 Fix Add Bucket Lifecycle Rule
  portal-ui/src/screens/Console/Buckets/BucketDetails/AddLifecycleModal.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/BucketLifecyclePanel.tsx
  portal-ui/src/screens/Console/Buckets/BucketDetails/EditLifecycleConfiguration.tsx
  portal-ui/src/screens/Console/Common/FormComponents/CodeMirrorWrapper/CodeMirrorWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/InputBoxWrapper/InputBoxWrapper.tsx
  portal-ui/src/screens/Console/Common/FormComponents/SelectWrapper/SelectWrapper.tsx
  restapi/user_buckets_lifecycle.go
Labels: Needed

#1809 Identity Provider screen for TenantDetails
  models/idp_configuration.go
  operatorapi/embedded_spec.go
  operatorapi/operations/operator_api.go
  operatorapi/operations/operator_api/tenant_identity_provider.go
  operatorapi/operations/operator_api/tenant_identity_provider_parameters.go
  operatorapi/operations/operator_api/tenant_identity_provider_responses.go
  operatorapi/operations/operator_api/tenant_identity_provider_urlbuilder.go
  operatorapi/operations/operator_api/update_tenant_identity_provider.go
  operatorapi/operations/operator_api/update_tenant_identity_provider_parameters.go
  operatorapi/operations/operator_api/update_tenant_identity_provider_responses.go
  operatorapi/operations/operator_api/update_tenant_identity_provider_urlbuilder.go
  operatorapi/tenant_add.go
  operatorapi/tenants.go
  portal-ui/src/common/SecureComponent/permissions.ts
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantEncryption.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantIdentityProvider.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSecurity.tsx
  portal-ui/src/screens/Console/Tenants/types.ts
  swagger-operator.yml
Labels: blocked

#1819 Correcting the testing package in Operator API Tests
  .github/workflows/jobs.yaml
  Makefile
  operator-integration/tenant_test.go
Labels: Operator

#1833 Adding unittest under user_watch.go
  .github/workflows/jobs.yaml
  restapi/user_watch_test.go
Labels: enhancement

#1835 Adding test to cover registerAdminArnsHandlers()
  .github/workflows/jobs.yaml
  integration/admin_api_integration_test.go
Labels: enhancement

#1846 Fix early context cancellation when downloading/previewing object
  restapi/user_objects.go
Labels: Needed

#1851 Correcting error message to be same as our code
  restapi/user_watch_test.go
Labels: enhancement

#1850 Test for invalid url in getWatchOptionsFromReq()
  .github/workflows/jobs.yaml
  restapi/user_watch_test.go
Labels: enhancement

#1848 Test for Get Object with Preview
  .github/workflows/jobs.yaml
  integration/objects_test.go
  integration/user_api_bucket_test.go
  restapi/user_objects.go
Labels: enhancement

#1865 Updated insecure dependencies
  portal-ui/package.json
  portal-ui/yarn.lock
Labels: Needed

#1871 Recalibrating our coverage threshold
  .github/workflows/jobs.yaml
Labels: bug

#1876 Removing unnecessary error check
  restapi/user_watch.go
Labels: enhancement

#1877 Test change password response
  restapi/user_account_test.go
Labels: enhancement

#1884 Fixing Permissions Tests Part 2
  .github/workflows/jobs.yaml
  portal-ui/tests/permissions-4/watch.ts
  portal-ui/tests/permissions-5/diagnostics.ts
  portal-ui/tests/permissions-6/heal.ts
Labels: enhancement

#1888 Fixed Objects list reload after file upload
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
Labels: bug, Needed

#1887 Remove redundant path from Tools
  portal-ui/src/screens/Console/Tools/Tools.tsx
Labels: enhancement, UI

#1898 Format Add Users/Groups, Fix bug on Add Service Account
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Groups/AddGroupScreen.tsx
  portal-ui/src/screens/Console/Users/AddUserScreen.tsx
Labels: Needed

#1914 Increase coverage threshold
  .github/workflows/jobs.yaml
Labels: enhancement

#1917 Fix profiling endpoint and adding tests
  integration/profiling_test.go
  restapi/admin_profiling.go
Labels: Needed

#1879 More Policy Tests, Set, List, Delete
  integration/config_test.go
  integration/policy_test.go
  restapi/admin_policies.go
Labels: enhancement

#1929 fix: parseTenantCertificates was ignoring cert-manager secrets
  operatorapi/tenants.go
Labels: Needed

#1931 Having Identity Provider configured via environment variables only
  Makefile
Labels: bug
