Repository minio/console, pull requests merged in 2022-08, with the labels that each got.

#2222 Add new section to register tenants with API key in operator
  portal-ui/src/screens/Console/Console.tsx
  portal-ui/src/screens/Console/Support/ApiKeyRegister.tsx
  portal-ui/src/screens/Console/Support/Register.tsx
  portal-ui/src/screens/Console/Support/RegisterOperator.tsx
  portal-ui/src/screens/Console/valid-routes.ts
Labels: Dependency

#2266 Catch error in gofmt
  Makefile
  verify-gofmt.sh
Labels: bug

#2283 Format all files after swagger-gen
  Makefile
Labels: enhancement
