Repository minio/console, pull requests merged in 2022-05, with the labels that each got.

#1954 Simplify SSO Integration test with Dex
  Makefile
  sso-integration/Dockerfile
  sso-integration/allaccess.json
  sso-integration/config.docker.yaml
  sso-integration/config/realm-export.json
  sso-integration/dex-requests.py
  sso-integration/logssorun2.sh
  sso-integration/set-sso.sh
  sso-integration/sso_test.go
Labels: enhancement

#1971 Increase coverage
  .github/workflows/jobs.yaml
Labels: enhancement

#1972 Upload coverage to play
  .github/workflows/jobs.yaml
Labels: enhancement

#1981 Correcting sso port to use our console server and increment coverage
  Makefile
  sso-integration/dex-requests.py
  sso-integration/sso_test.go
Labels: WIP

#2017 Update Operator API Test
  .github/workflows/console-sa-secret.yaml
  .github/workflows/deploy-tenant.sh
  operator-integration/tenant_test.go
Labels: enhancement

#2023 Increase coverage threshold
  .github/workflows/jobs.yaml
Labels: enhancement

#2026 Fixed tenant details infinite load loop
  portal-ui/src/screens/Console/Tenants/tenantsSlice.ts
Labels: bug, Needed

#2028 fix: capacity reported usage value
  portal-ui/src/common/utils.ts
  portal-ui/src/screens/Console/Dashboard/Prometheus/Widgets/CapacityItem.tsx
  portal-ui/src/screens/Console/Dashboard/Prometheus/utils.tsx
Labels: bug, Needed

#1997 To support multiple CSRs per tenant
  .github/workflows/deploy-tenant.sh
  models/csr_elements.go
  operator-integration/tenant_test.go
  operatorapi/embedded_spec.go
  operatorapi/operations/operator_api/list_tenant_certificate_signing_request_responses.go
  operatorapi/volumes.go
  portal-ui/tests/scripts/operator.sh
  portal-ui/tests/scripts/tenant-kes-encryption/kustomization.yaml
  portal-ui/tests/scripts/tenant-lite/kustomization.yaml
  swagger-operator.yml
Labels: enhancement

#2053 Add test for registerAdminArnsHandlers
  restapi/admin_arns_test.go
Labels: enhancement
