Repository minio/console, pull requests merged in 2022-03, with the labels that each got.

#1642 Reset File input value after file upload
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
Labels: bug, Needed

#1646 Fixed delete object behavior
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectDetailPanel.tsx
Labels: bug

#1651 Whitelist for preview files from the backend
  operatorapi/proxy.go
  restapi/user_objects.go
  restapi/utils.go
Labels: security, Needed

#1677 Validate basePath for console
  restapi/configure_console.go
Labels: security, Needed

#1678 Re-using code by implementing add bucket verification only once
  integration/user_api_bucket_test.go
Labels: enhancement

#1697 Increasing coverage threshold from 48% to 49.4%
  .github/workflows/jobs.yaml
Labels: enhancement

#1736 List tenants by namespace test
  .github/workflows/jobs.yaml
  operator-integration/tenant_test.go
Labels: Operator

#1707 Fix profile screen
  models/profiler_type.go
  models/profiling_start_request.go
  portal-ui/src/screens/Console/Support/Profile.tsx
  portal-ui/src/screens/Console/Tools/Tools.tsx
  portal-ui/src/screens/Console/valid-routes.ts
  restapi/admin_profiling.go
  restapi/admin_profiling_test.go
  restapi/doc.go
  restapi/embedded_spec.go
  restapi/operations/console_api.go
  swagger-console.yml
Labels: Needed

#1740 AWS Marketplace Integration Updates
  portal-ui/src/common/BackLink.tsx
  portal-ui/src/common/utils.ts
  portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/NameTenantMain.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/TenantSize.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/utils.tsx
  portal-ui/src/screens/Console/Tenants/actions.ts
  portal-ui/src/screens/Console/Tenants/reducer.ts
  portal-ui/src/screens/Console/Tenants/reducers/add-tenant-reducer.ts
  portal-ui/src/screens/Console/Tenants/types.ts
Labels: Needed

#1749 Updated dependencies for yarn audit issues
  portal-ui/package.json
  portal-ui/yarn.lock
Labels: Needed

#1771 List Users With Access to a Given Bucket Integration Test
  .github/workflows/jobs.yaml
  integration/admin_api_integration_test.go
Labels: enhancement

#1772 fix: pass original http response code to proxy response
  operatorapi/proxy.go
Labels: Needed

#1784 Hide redundant folder references in console
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
Labels: Needed
