Repository minio/console, pull requests merged in 2022-10, with the labels that each got.

#2359 Improve Permissions Tests Part 1
  .github/workflows/jobs.yaml
  portal-ui/tests/permissions-A/iamPolicies.ts
  portal-ui/tests/permissions-B/bucketWritePrefixOnly.ts
Labels: enhancement

#2364 Removed position fixed to tenant size preview
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/NameTenantMain.tsx
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantYAML.tsx
Labels: Needed

#2366 Splitting Operator UI Tests for faster execution
  .github/workflows/jobs.yaml
  portal-ui/tests/operator/login/login.ts
  portal-ui/tests/operator/tenant/test-1/tenant-test-1.ts
  portal-ui/tests/operator/tenant/test-2/tenant-test-2.ts
  portal-ui/tests/operator/tenant/test-3/tenant-test-3.ts
  portal-ui/tests/operator/tenant/test-4/tenant-test-4.ts
Labels: enhancement

#2393 Moving away from Nancy
  .github/workflows/jobs.yaml
Labels: blocked

#2392 Fixes to Multiple IDP support in console
  models/login_details.go
  models/redirect_rule.go
  operatorapi/embedded_spec.go
  operatorapi/login.go
  pkg/auth/idp.go
  pkg/auth/idp/oauth2/config.go
  pkg/auth/idp/oauth2/const.go
  pkg/auth/idp/oauth2/provider.go
  pkg/auth/idp/oauth2/provider_test.go
  portal-ui/src/screens/LoginPage/LoginPage.tsx
  portal-ui/src/screens/LoginPage/loginSlice.ts
  portal-ui/src/screens/LoginPage/types.ts
  portal-ui/src/utils/sortFunctions.ts
  restapi/embedded_spec.go
  restapi/policy/policies.go
  restapi/user_login.go
  sso-integration/sso_test.go
  swagger-console.yml
  swagger-operator.yml
Labels: bug, needed
