Repository minio/console, pull requests merged in 2022-06, with the labels that each got.

#2131 Relaxing tests when play is down
  .github/workflows/jobs.yaml
Labels: enhancement

#2098 Delete Tenant Test
  operator-integration/tenant_test.go
Labels: WIP

#2138 Improving our Operator Test in console
  portal-ui/tests/scripts/operator.sh
Labels: enhancement

#2145 Fixed issues in Replication rules screens
  integration/user_api_bucket_test.go
  portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplicationModal.tsx
  restapi/admin_remote_buckets.go
Labels: bug, Needed

#2147 Avoid the crash in the test
  operator-integration/tenant_test.go
Labels: enhancement

#2150 Add object-level error message display in Downloads/Uploads panel
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectDetailPanel.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/VersionsNavigator.tsx
  portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
  portal-ui/src/screens/Console/Common/ObjectManager/ObjectHandled.tsx
  portal-ui/src/screens/Console/ObjectBrowser/RenameLongFilename.tsx
  portal-ui/src/screens/Console/ObjectBrowser/objectBrowserSlice.ts
  portal-ui/src/screens/Console/ObjectBrowser/types.ts
Labels: enhancement
