Repository minio/console, pull requests merged in 2022-09, with the labels that each got.

#2295 To repair SSO test
  .github/workflows/jobs.yaml
Labels: Fixed

#2294 Support for providing Tenant client certificates
  go.mod
  go.sum
  models/create_tenant_request.go
  models/tenant_security_response.go
  models/tls_configuration.go
  models/update_tenant_security_request.go
  operatorapi/embedded_spec.go
  operatorapi/tenant_add.go
  operatorapi/tenant_get.go
  operatorapi/tenants.go
  operatorapi/tenants_helper.go
  operatorapi/tenants_helper_test.go
  operatorapi/tenants_test.go
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Encryption.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Security.tsx
  portal-ui/src/screens/Console/Tenants/AddTenant/createTenantSlice.ts
  portal-ui/src/screens/Console/Tenants/AddTenant/thunks/createTenantThunk.ts
  portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSecurity.tsx
  portal-ui/src/screens/Console/Tenants/types.ts
  swagger-operator.yml
Labels: Needed

#2292 To repair the Operator API Tests & Operator UI Tests
  .github/workflows/jobs.yaml
  portal-ui/tests/scripts/operator.sh
  tests/common.sh
Labels: enhancement

#2299 To migrate Permissions Tests Part 1 test
  .github/workflows/jobs.yaml
Labels: Test migration

#2309 To migrate all testcafe
  .github/workflows/jobs.yaml
Labels: Test migration

#2318 To add missing file for coverage
  .github/workflows/jobs.yaml
Labels: enhancement

#2281 Adds a logout view which enables minio to logout when using OIDC
  portal-ui/src/MainRouter.tsx
  portal-ui/src/screens/Console/Menu/ConsoleMenuList.tsx
  portal-ui/src/screens/Console/Menu/Menu.tsx
  portal-ui/src/screens/LogoutPage/LogoutPage.tsx
Labels: enhancement

#2333 Fix oauth state generation for OIDC login
  operatorapi/login.go
  pkg/auth/idp.go
  pkg/auth/idp/oauth2/config.go
  pkg/auth/idp/oauth2/provider.go
  pkg/auth/idp/oauth2/provider_test.go
  restapi/user_login.go
Labels: Needed

#2346 Fix IDP not having same salt/passphrase across pods
  pkg/auth/idp/oauth2/config.go
Labels: Needed
