Repository minio/console, pull requests merged in 2022-01, with the labels that each got.

#1359 Use default storage class for postgre/prometheus if not user specified
  operatorapi/operator_tenants.go
  operatorapi/utils.go
Labels: Needed

#1358 Add Azure marketplace VM choices
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/utils.tsx
Labels: Needed

#1377 Fix bug on opertator UI where metrics was showing the menu
  portal-ui/src/common/SecureComponent/permissions.ts
Labels: bug, Operator

#1418 Fixed issue where storage class resets when changing between tabs
  portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/NameTenantMain.tsx
Labels: bug, WIP, Needed
